// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	sql "github.com/gofreego/database/sql"
	mock "github.com/stretchr/testify/mock"
)

// Record is an autogenerated mock type for the Record type
type Record struct {
	mock.Mock
}

// Columns provides a mock function with no fields
func (_m *Record) Columns() []*sql.Field {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Columns")
	}

	var r0 []*sql.Field
	if rf, ok := ret.Get(0).(func() []*sql.Field); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sql.Field)
		}
	}

	return r0
}

// ID provides a mock function with no fields
func (_m *Record) ID() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// IdColumn provides a mock function with no fields
func (_m *Record) IdColumn() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IdColumn")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Scan provides a mock function with given fields: row
func (_m *Record) Scan(row sql.Row) error {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(sql.Row) error); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetDeleted provides a mock function with given fields: deleted
func (_m *Record) SetDeleted(deleted bool) {
	_m.Called(deleted)
}

// SetID provides a mock function with given fields: id
func (_m *Record) SetID(id int64) {
	_m.Called(id)
}

// Table provides a mock function with no fields
func (_m *Record) Table() *sql.Table {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Table")
	}

	var r0 *sql.Table
	if rf, ok := ret.Get(0).(func() *sql.Table); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Table)
		}
	}

	return r0
}

// Values provides a mock function with no fields
func (_m *Record) Values() []interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Values")
	}

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func() []interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	return r0
}

// NewRecord creates a new instance of Record. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecord(t interface {
	mock.TestingT
	Cleanup(func())
}) *Record {
	mock := &Record{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
